version: 0.2
run-as: root
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      java: corretto11
    commands:
      - echo Instal completed on `date`
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew build buildZip
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation package --template-file template.yml --s3-bucket dmitriy-zosimov-lambda --output-template-file package.yml
artifacts:
  files:
    - package.yml